// src/components/Toolbar.svelte
<!--
PokeBook -- Pokeghost's poetry noteBook
Copyright (C) 2024, 2026 Pokeghost.

PokeBook is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

PokeBook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
-->

<script lang="ts">
	import { padFonts } from '$lib/constants/PadFonts';
	import { poemPadJustification } from '$lib/stores/poemPadJustification';
	import { writingPadFont } from '$lib/stores/writingPadFont';
	import type { ToolbarItem } from '$lib/types';
	import { ChevronDown } from 'lucide-svelte';
	import AlignCenter from 'lucide-svelte/icons/align-center';
	import AlignLeft from 'lucide-svelte/icons/align-left';
	import AlignRight from 'lucide-svelte/icons/align-right';
	import FontSize from './FontSize.svelte';

	export let actions: ToolbarItem[];
</script>

<div class="toolbar-menu">
	<div class="button-group">
		<button
			on:click={() => ($poemPadJustification = 'left')}
			class={`button ${$poemPadJustification === 'left' ? 'active' : ''}`}
		>
			<AlignLeft />
		</button>
		<button
			on:click={() => ($poemPadJustification = 'center')}
			class={`button ${$poemPadJustification === 'center' ? 'active' : ''}`}
		>
			<AlignCenter />
		</button>
		<button
			on:click={() => ($poemPadJustification = 'right')}
			class={`button ${$poemPadJustification === 'right' ? 'active' : ''}`}
		>
			<AlignRight />
		</button>
	</div>
	<div class="settings-select">
		<select bind:value={$writingPadFont} style="margin: 0; min-width: 130px;">
			{#each padFonts as option}
				<option value={option.value}>
					{option.label}
				</option>
			{/each}
		</select>
		<div class="settings-select-chevron-wrapper" style="margin-top: -5px">
			<ChevronDown />
		</div>
	</div>
	<FontSize />
	{#each actions as action}
		<button on:click={() => action.action()} class="button" disabled={action.disabled}>
			<svelte:component this={action.icon} />
			{action.label}
		</button>
	{/each}
</div>

// pokebook4/src/components/Toolbar.tsx
/*
PokeBook -- Pokeghost's poetry noteBook
Copyright (C) 2024 Pokeghost.

PokeBook is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

PokeBook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
*/

import { For, type Component } from "solid-js";

import { usePreferences } from "./PreferencesProvider";

import type { ToolbarItem } from "@lib/types";

import { AlignCenter, AlignLeft, AlignRight } from "lucide-solid";
import { Dynamic } from "solid-js/web";

const Toolbar: Component<{ actions: ToolbarItem[] }> = (props) => {
  const [pref, setPref] = usePreferences();

  return (
    <div class="toolbar-menu">
      <div class="button-group">
        <button
          onClick={() => setPref("poemPadJustification", "left")}
          class="button"
          classList={{ active: pref.poemPadJustification === "left" }}
        >
          <AlignLeft />
        </button>
        <button
          onClick={() => setPref("poemPadJustification", "center")}
          class="button"
          classList={{ active: pref.poemPadJustification === "center" }}
        >
          <AlignCenter />
        </button>
        <button
          onClick={() => setPref("poemPadJustification", "right")}
          class="button"
          classList={{ active: pref.poemPadJustification === "right" }}
        >
          <AlignRight />
        </button>
      </div>
      <For each={props.actions}>
        {(action) => (
          <button class="button" onClick={() => action.action()}>
            <Dynamic component={action.icon} />
            {action.label}
          </button>
        )}
      </For>
    </div>
  );
};

export default Toolbar;
