// pokebook/src/routes/stash/poem/+page.svelte
<!--
PokeBook -- Pokeghost's poetry noteBook
Copyright (C) 2023-2025 Pokeghost.

PokeBook is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

PokeBook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
-->

<script lang="ts">
	import { goto } from '$app/navigation';
	import { onDestroy, onMount } from 'svelte';

	import toast from 'svelte-french-toast';

	import {
		currentPoemBody,
		currentPoemName,
		currentPoemNote,
		currentPoemUri
	} from '$lib/stores/currentPoem';
	import { discardFunction, saveFunction } from '$lib/stores/poemFunctionsStore';
	import { storageMode } from '$lib/stores/storageMode';

	import { sharePoem } from '$lib/actions/sharePoem';
	import PoemCacheManager from '$lib/plugins/PoemCacheManager.svelte';
	import Poem from '$lib/models/Poem';
	import { t } from '$lib/translations';
	import { GLOBAL_TOAST_POSITION, GLOBAL_TOAST_STYLE } from '$lib/util/constants';
	import FilesystemWithPermissions from '$lib/util/FilesystemWithPermissions';
	import { Encoding } from '@capacitor/filesystem';
	import { XMLBuilder } from 'fast-xml-parser';

	import Save from 'lucide-svelte/icons/save';
	import Share2 from 'lucide-svelte/icons/share-2';
	import Trash2 from 'lucide-svelte/icons/trash-2';

	import UnsavedChangesToast from '../../../components/UnsavedChangesToast.svelte';
	import Workspace from '../../../components/Workspace.svelte';

	let unsavedChangesToastId: string;

	let thinking = true;

	let poemProps = { name: currentPoemName, body: currentPoemBody };
	let noteProps = currentPoemNote;

	// TODO: Maybe using stores here is not the best choice but I don't want to wreck everything now
	$: {
		if (!thinking)
			FilesystemWithPermissions.writeFile({
				path: `${$currentPoemUri}.tmp`,
				data: new XMLBuilder({ format: true }).build({
					name: $currentPoemName,
					text: $currentPoemBody,
					note: $currentPoemNote
				}),

				encoding: Encoding.UTF8
			});
	}

	// TODO: Temporary solution until the new version of `svelte-french-toast` with props is published
	$saveFunction = async () => {
		await toast.promise(
			save(),
			{
				loading: `${$t('toasts.savingPoem')}`,
				success: `${$t('toasts.poemSaved')}`,
				error: `${$t('errors.poemSaveError')}`
			},
			{
				position: GLOBAL_TOAST_POSITION,
				style: GLOBAL_TOAST_STYLE
			}
		);
	};
	$discardFunction = async () => {
		await PoemCacheManager.unsetUnsavedStatus($storageMode, $currentPoemUri);
		await Poem.delete(`${$currentPoemUri}.tmp`, 'local');
		goto('/stash', { replaceState: false });
	};

	const deletePoemAction = async () => {
		if (confirm(`${$t('toasts.forgetConfirm')}`)) {
			await toast.promise(
				deletePoem(),
				{
					loading: `${$t('toasts.deletingPoem')}`,
					success: `${$t('toasts.deletedPoem')}`,
					error: `${$t('errors.poemDeleteError')}`
				},
				{
					position: GLOBAL_TOAST_POSITION,
					style: GLOBAL_TOAST_STYLE
				}
			);
		}
	};

	async function save() {
		const newPoemUri = await Poem.update(
			{ name: $currentPoemName, text: $currentPoemBody, note: $currentPoemNote },
			$currentPoemUri,
			$storageMode
		);

		if (newPoemUri) $currentPoemUri = newPoemUri;

		await deleteTmpFile($currentPoemUri);
	}

	async function deletePoem() {
		await Poem.delete($currentPoemUri, $storageMode);
		await deleteTmpFile($currentPoemUri);
		await PoemCacheManager.popCacheRecord($storageMode, $currentPoemUri);
		clearCurrentPoemStorage();
		await goto('/stash', { invalidateAll: true });
	}

	let actions = [
		// TODO: Bad, bad, bad, bad!!!
		{ icon: Save, action: $saveFunction, label: $t('workspace.savePoem') },
		{
			icon: Share2,
			action: () =>
				sharePoem($currentPoemName, $currentPoemBody, $t('toasts.poemCopiedToClipboard')),
			label: $t('workspace.sharePoem')
		},
		{ icon: Trash2, action: deletePoemAction, label: $t('workspace.forgetPoem') }
	];

	onMount(async () => {
		if (
			(await PoemCacheManager.getCacheRecord($storageMode, $currentPoemUri))?.unsavedChanges === true
		) {
			unsavedChangesToastId = toast(UnsavedChangesToast, {
				duration: Infinity,
				position: GLOBAL_TOAST_POSITION,
				style: GLOBAL_TOAST_STYLE
			});
			const { name, text, note } = await Poem.load(`${$currentPoemUri}.tmp`, 'local');
			$currentPoemName = name;
			$currentPoemBody = text;
			$currentPoemNote = note;

			thinking = false;
		} else {
			try {
				const poem = await Poem.load($currentPoemUri, $storageMode);
				if (poem) {
					$currentPoemName = poem.name;
					$currentPoemBody = poem.text;
					$currentPoemNote = poem.note;
				}
			} catch (e) {
				if (e instanceof Error) {
					toast.error($t(e.message), {
						position: GLOBAL_TOAST_POSITION,
						style: GLOBAL_TOAST_STYLE
					});
				}
			}
			thinking = false;
		}
	});

	onDestroy(() => {
		toast.dismiss(unsavedChangesToastId);
	});

	function unsavedChangesHandler() {
		PoemCacheManager.setUnsavedStatus($storageMode, $currentPoemUri);
	}

	function clearCurrentPoemStorage() {
		$currentPoemBody = $currentPoemName = $currentPoemNote = $currentPoemUri = '';
	}

	async function deleteTmpFile(fileUri: string) {
		try {
			await Poem.delete(`${fileUri}.tmp`, 'local');
		} catch (_) {}
	}
</script>

{#if thinking}
	<div class="placeholder-text-wrapper">
		<p>Loading...</p>
	</div>
{:else}
	<Workspace {poemProps} {noteProps} {actions} {unsavedChangesHandler} />
{/if}

// pokebook4/src/routes/Poem.tsx
/*
PokeBook -- Pokeghost's poetry noteBook
Copyright (C) 2024 Pokeghost.

PokeBook is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

PokeBook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
*/

import {
  createEffect,
  createResource,
  createSignal,
  onMount,
  Show,
} from "solid-js";
import { createStore } from "solid-js/store";

import { useParams } from "@solidjs/router";

import { Filesystem } from "@lib/plugins/Filesystem";

import type { PoemEntity, ToolbarItem } from "@lib/types";
import { type Component } from "solid-js";

import NoteNotepad from "@components/NoteNotepad";
import PoemNotepad from "@components/PoemNotepad";
import Toolbar from "@components/Toolbar";
import Workspace from "@components/Workspace";

const Poem = () => {
  const params = useParams();
  const [loading, setLoading] = createSignal(true);
  const [poem, setPoem] = createStore({} as PoemEntity);

  onMount(async () => {
    const poemFile = (await Filesystem.readFile({ path: `/${params.id}.json` }))
      .data;
    setPoem(JSON.parse(poemFile as string) as PoemEntity);
    setLoading(false);
  });

  createEffect(() => {
    console.log("current poem state", JSON.stringify(poem));
    Filesystem.writeFile({
      path: `/${params.id}.tmp.json`,
      data: JSON.stringify(poem),
    });
  });

  const actions: ToolbarItem[] = [];

  const poemNotepad: Component = () => (
    <PoemNotepad
      title={poem.name}
      text={poem.text}
      titleInputHandler={(e) => setPoem("name", e.currentTarget.value)}
      inputHandler={(e) => setPoem("text", e.currentTarget.value)}
    />
  );
  const noteNotepad: Component = () => (
    <NoteNotepad
      text={poem.note}
      inputHandler={(e) => setPoem("note", e.currentTarget.value)}
    />
  );

  return (
    <Show when={!loading()} fallback={<div>Loading...</div>}>
      <div class="toolbar">
        <Toolbar actions={actions} />
      </div>
      <Workspace notepads={[poemNotepad, noteNotepad]} />
    </Show>
  );
};

export default Poem;
